print("Sequence of numbers generated by range(5)")
for i in range(5):
    print(i, end = ' ')

print("\nSequence of numbers generated by range(3,10)")
for j in range(3, 10):
    print(j, end = ' ')

print("\nSequence of numbers generated by range(4,13,3)")
for k in range(4, 13, 3):
    print(k, end = ' ')

print("\nSequence of numbers generated by range(15,5,-2)")
for l in range(15, 5, -2):
    print(l, end = ' ')

print("\nSequence of numbers generated by range(5,3)")
for m in range(5, 3):
    print(m, end = ' ')
